version: "3.9"


services:

  faststream_app:
    build:
      context: ../..
      dockerfile: Dockerfile
    image: main
    env_file:
      - .env
    command: ["make", "app"]
    ports:
      - 9000:9000

  data_generation:
    image: main
    env_file:
      - .env
    command: ["make", "data"]
    depends_on:
      - faststream_app
